---
- name: Deploy config
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongodb
    group: mongodb
    mode: 0644
  notify: restart mongod

- name: Start mongod
  service:
    name: mongod
    state: started
    enabled: yes
