---
- name: Include prepare.yml
  include_tasks: prepare.yml

- name: Include install.yml
  include_tasks: install.yml

- name: Include service.yml
  include_tasks: service.yml

- name: Include configure.yml
  include_tasks: configure.yml
