---
- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ mongodb_package_requirements }}"

- name: Install MongoDB Key
  apt_key:
    url: "{{ mongodb_key }}"
    state: present

- name: Add MongoDB Repository
  apt_repository:
    repo: "{{ mongodb_repository }}"
    state: present
    update_cache: yes

